### ISSUE TITLE
Something wrong happened when building

### ISSUE THREAD

**Issue by poberwong** [reactnativecomponent/react-native-netease-im#12]
## version
* system: 10.13.1
* Xcode: 9.1
* react-native: 0.50.3
some syntax need to be upgraded ？

![image](https://user-images.githubusercontent.com/8554661/33069257-ebf54208-ceee-11e7-9e5b-46e94c1994fe.png)

**Comment by hzlgit** [comment]
NIMSDK版本4.1.0

**Comment by poberwong** [comment]
merged 分支 + 0.50.3 + 0.41 的 SDK
merged 分支见 @cpunion 的分支
