### ISSUE TITLE
和codepush冲突

### ISSUE THREAD

**Issue by luwu1991** [reactnativecomponent/react-native-netease-im#15]
我的项目中同时使用你的库和react-native-code-push，都使用了SSZipArchive这个库，但这二个库中的SSZipArchive文件代码有些不同的地方，所以也没法删除一个，请问下你的库中使用有SSZipArchive的地方吗？或者你可以看下react-native-code-push中使用的SSZipArchive，能给我一个解决办法最好了。谢谢~

**Comment by hzlgit** [comment]
手动安装code-push,然后移除code-push中的SSZipArchive使用cocoapods中的库，这样其他库都可以使用SSZipArchive

**Comment by luwu1991** [comment]
@hzlgit 但是code-push中的和通过cocopods 代码会有一些差别，这个没有影响吗？

**Comment by hzlgit** [comment]
@luwu1991 如果有问题，那cocoapods中你可以安装code-push的版本

**Comment by zpfblockchains** [comment]
@luwu1991 最后怎么解决的
