### ISSUE TITLE
Type 只能在 .ts 文件中使用

### ISSUE THREAD

**Issue by wangeek** [reactnativecomponent/react-native-netease-im#16]
在这行代码中 `limit:Number` 指定了type。

https://github.com/reactnativecomponent/react-native-netease-im/blob/150d243671fc6dfe8905499f37b00ef9199d104a/im/Session.js#L83

**Comment by hzlgit** [comment]
装个 flow

**Comment by wangeek** [comment]
我的意思是这里代码不规范，应该修正代码
