### ISSUE TITLE
自定义消息解析错误

### ISSUE THREAD

**Issue by 54sword** [reactnativecomponent/react-native-netease-im#22]
使用API发送自定义消息
```
NimSession.sendCustomMessage({Width:260,Height:100,pushContent:'发来一条自定义消息',recentContent:'[自定义消息]'})；
```
发送成功后，然后通过如下监听事件，可以获取到数据是正常的。
```
NativeAppEventEmitter.addListener("observeMsgStatus", (msg)=>{});
```
![01dbf0cb-af85-4540-af81-f5791242136a](https://user-images.githubusercontent.com/888115/40108377-4442c8e0-592d-11e8-9be0-15c52818ef8a.png)

但问题来了，关闭app，下次打开app的时候，通过如下方式获取聊天记录的时候，数据就不正常了，msgType没有了，extend也没有了。
```
NimSession.queryMessageListEx(session.messageId,20).then(()=>{});
```
![2018-05-16 5 11 07](https://user-images.githubusercontent.com/888115/40108849-abd4f3e2-592e-11e8-8b22-5fc471a7d15c.png)

**Comment by hzlgit** [comment]
@54sword 需要配置自定义消息解析器。

**Comment by 54sword** [comment]
@hzlgit 但通过如下API，获取聊天记录数据，自定义消息中没有msgType和extend属性，我判断不了它是否是自定义消息，拿不到extend数据，做不了视图的显示。然后web端，接收的自定义消息数据都是正常的。
```
NimSession.queryMessageListEx(session.messageId,20).then(()=>{});
```

**Comment by hzlgit** [comment]
@54sword ios还是安卓？你确定配置了自定义消息解析器没有

**Comment by 54sword** [comment]
@hzlgit 是ios。然后“自定义消息解析器”我有点不太明白，这个需要在哪里配置？

**Comment by hzlgit** [comment]
@54sword 配置里面没写，后面补上，可以看demo里面的 https://github.com/reactnativecomponent/react-native-chat-demo/blob/master/ios/ImDemo/AppDelegate.m 47行

**Comment by 54sword** [comment]
@hzlgit 泪流满面😭，可以了！
