### ISSUE TITLE
RN0.44.3 集成后编译问题集合

### ISSUE THREAD

**Issue by Gd362660870** [reactnativecomponent/react-native-netease-im#3]
在ios运行出现libSSZipArchive.a库与libRCTHotUpdate.a 出现冲突估计重复枚举问题。
然后去掉SSZipArchive 编译成功！
SSZipArchive是一个解压工具，接口也没有相关功能？
想问：想问去掉后会出现其他bug吗？

**Comment by hzlgit** [comment]
这属于包的冲突问题
