### ISSUE TITLE
react-native-netease-im是否支持用户一对一聊天？

### ISSUE THREAD

**Issue by RowgerGo** [reactnativecomponent/react-native-netease-im#32]
我看到云信文档里面有一对一聊天，使用
`[[[NIMSDK sharedSDK] chatManager] sendMessage:message toSession:session error:nil]`就行，但是在react-native-netease-im这个库里面没有找到对应的一对一聊天的方法，请问react-native-netease-im是否支持用户一对一聊天？

**Comment by hzlgit** [comment]
支持
