### ISSUE TITLE
library not found for -lCocoaLumberjack

### ISSUE THREAD

**Issue by vivi19** [reactnativecomponent/react-native-netease-im#34]
用命令行可以打开，但是xcode打开就会报错，
`ld: library not found for -lCocoaLumberjack
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

`ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/CocoaLumberjack'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/DoubleConversion'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/Folly'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/QBImagePickerController'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/RNGestureHandler'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/RNImageCropPicker'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/RNSVG'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/RSKImageCropper'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/React'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/SDWebImage'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/glog'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/react-native-amap-geolocation'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/react-native-amap3d'
ld: warning: directory not found for option '-L/Users/will/Library/Developer/Xcode/DerivedData/ImDemo-bdhujzdymxudiyfxmsmlobomlaut/Build/Products/Debug-iphonesimulator/yoga'
`

**Comment by hzlgit** [comment]
安装CocoaLumberjack即可
