### ISSUE TITLE
react-native0.62中报错，不能使用，求解决

### ISSUE THREAD

**Issue by liubi520** [reactnativecomponent/react-native-netease-im#40]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/11856589/79200677-62a70400-7e69-11ea-9f8f-bf40ab6473d1.png">

**Comment by liubi520** [comment]
在react-native 0.62中包报错错误信息如下：
eact-native-netease-im/ios/RNNeteaseIm/RNNeteaseIm/PrefixHeader.pch:10:9: 'NIMSDK/NIMSDK.h' file not found

/ios/Pods/Headers/Public/Flipper-Folly/folly/string.h:20:10: 'cstdarg' file not found

Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: Could not build module 'Darwin'

Developer/SDKs/iPhoneOS13.2.sdk/usr/include/dispatch/dispatch.h:25:10: Could not build module 'Darwin'

Developer/SDKs/iPhoneOS13.2.sdk/usr/include/os/object.h:25:10: Could not build module 'Darwin'

SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: Could not build module 'CoreFoundation'

Developer/SDKs/iPhoneOS13.2.sdk/usr/include/objc/objc.h:31:10: Could not build module 'Darwin'

/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:27:10: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreServices.framework/Headers/UTCoreTypes.h:19:10: Could not build module 'CoreFoundation'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: Could not build module 'Foundation'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:8:10: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:11:10: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: Could not build module 'Foundation'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLDefines.h:8:9: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/IOSurface.framework/Headers/IOSurfaceBase.h:12:10: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImageDefines.h:10:10: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:16:10: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/ImageIO.framework/Headers/ImageIOBase.h:11:10: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTDefines.h:12:10: Could not build module 'Darwin'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:8:9: Could not build module 'Foundation'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/NSString+UserNotifications.h:8:9: Could not build module 'Foundation'

**Comment by ma6566966** [comment]
解决了吗?我也遇到一样的问题

**Comment by liubi520** [comment]
No, I give up on this




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ma6566966"<notifications@github.com&gt;; 
发送时间: 2020年5月18日(星期一) 下午3:01
收件人: "reactnativecomponent/react-native-netease-im"<react-native-netease-im@noreply.github.com&gt;; 
抄送: "610112074"<610112074@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [reactnativecomponent/react-native-netease-im] react-native0.62中报错，不能使用，求解决 (#40)





 
解决了吗?我也遇到一样的问题

**Comment by songxiaoliang** [comment]
@liubi520 你好，请问解决了吗？

**Comment by noway** [comment]
I'm experiencing the same issue, any workaround?

**Comment by noway** [comment]
I fixed it by searching for `HEADER_SEARCH_PATHS` in Buld Settings and then deleting all the custom overrides I had for that setting.
